CREATE TABLE IF NOT EXISTS partitions(id TEXT PRIMARY KEY,name TEXT NOT NULL,color TEXT NOT NULL,armed INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS plans(id TEXT PRIMARY KEY,name TEXT NOT NULL,geometry TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rooms(id INTEGER PRIMARY KEY AUTOINCREMENT,plan_id TEXT NOT NULL REFERENCES plans(id),name TEXT NOT NULL,x REAL,y REAL,w REAL,h REAL,partition_id TEXT REFERENCES partitions(id));
CREATE TABLE IF NOT EXISTS devices(id TEXT PRIMARY KEY,plan_id TEXT NOT NULL REFERENCES plans(id),type TEXT NOT NULL,name TEXT NOT NULL,room TEXT NOT NULL,x REAL,y REAL,label TEXT,base REAL,partition_id TEXT REFERENCES partitions(id),state TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,ts INTEGER NOT NULL,level TEXT NOT NULL DEFAULT '',message TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS ev_ts ON events(ts DESC);
